import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import App from './components/App' // main react component
import bridge from 'extendscriptkit/js/bridge' // CSInterface instance
import cnsl from 'extendscriptkit/js/console'
import configureStore from './store/configureStore'
import { getAppProperties } from './actions/app'

// weirdo imports
import style from '../style.scss' // load sass stylesheet contents (sassify transform)
const fs = require('fs') // files that are readFileSync'd will be embedded in final bundle (BRFS transform)
const path = nodeRequire('path') // path utility (node.js require)

cnsl(bridge) // add console.log / console.error support

const initialState = {}
const store = configureStore(initialState)

// add stylesheet
const styleEl = document.createElement('style')
styleEl.innerHTML = style
document.body.appendChild(styleEl)

// create DOM element that will contain the App
const appEl = document.createElement('div')
appEl.className = 'app'
document.body.appendChild(appEl)

// render the App react component into the app element
ReactDOM.render((
  <Provider store={store}>
    <App />
  </Provider>
), appEl)

function onBundleLoaded() {
  // dispatch a redux action because we can
  store.dispatch(getAppProperties())
}

// evaluate the bundle (generated by browserify)
bridge.evalScript(fs.readFileSync('./build/bundle.jsx', 'utf8'), onBundleLoaded)
