require('./src/js/boot')
const fs = require('fs') // not used, fs.readFileSync are replaced with actual content by "brfs" transform
const { evalJsx } = require('./src/js/bridge')
// require('whatwg-fetch')

// evaluate some shims for ExtendScript
evalJsx(fs.readFileSync('./src/jsx/shim.jsx', 'utf8'))
evalJsx(fs.readFileSync('./node_modules/extendscript-es5-shim/Object/keys.js', 'utf8'))
evalJsx(fs.readFileSync('./node_modules/extendscript-es5-shim/Object/defineProperty.js', 'utf8'))

// evaluate the bundle (generated by browserify)
evalJsx(fs.readFileSync('./build/bundle.jsx', 'utf8'))

// fetch('https://vespavibes.com/api/layers/world-trip-shortest') //,berlin-istanbul,istanbul-tehran,tehran-imphal,imhal-thong-pha-phum,thong-pha-phum-new-zealand,rijckholt-paris,to-berlin,berlin-sardegna-berlin,berlin-portugal,portugal-maastricht,to-berlin-with-roj
//   .then(res => res.text())
//   .then(json => {
//     evalJsx(`
//       eval('var worldTrip = ${json}');
//       console.log(worldTrip['world-trip-shortest']['type']);
//     `)
//   })
